# vim: ts=2 sw=2 et ft=yaml
---
sudo: false
language: python
matrix:
 include:
 - python: "2.7"
   os: linux
   dist: xenial
   env: TOXENV=py27
 - python: "3.4"
   os: linux
   dist: xenial
   env: TOXENV=py34
 - python: "3.5"
   os: linux
   dist: xenial
   env: TOXENV=py35
 - python: "3.6"
   os: linux
   dist: xenial
   env: TOXENV=py36
 - python: "3.7"
   os: linux
   dist: xenial
   env: TOXENV=py37
before_install:
 # Show the current setuptools version
 - python -c "import setuptools; print(setuptools.__version__)"
install:
 - pip install wheel tox
 - python setup.py install bdist_wheel
 - pip install dist/sshadder-*.whl
script:
 - tox -e ${TOXENV} --installpkg ./dist/sshadder-*.whl
